FROM mongo:latest

# RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
# COPY seed.py /data/db-seed/
# COPY mongo-seed.sh /docker-entrypoint-initdb.d/

# RUN chmod +x /docker-entrypoint-initdb.d/mongo-seed.sh
