FROM mongo:latest

# COPY init.json /init.json
# COPY mongo-seed.sh /mongo-seed.sh
# RUN chmod +x /mongo-seed.sh

# RUN mongoimport --host localhost --db matches --collection matches --type json --file init.json --jsonArray

