name: Deploy frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # Replace with your AWS region

      - name: Create .env.production file
        run: |
          echo "VITE_AUTH0_CLIENTID=${{ secrets.VITE_AUTH0_CLIENTID }}" >> .env.production
          echo "VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}" >> .env.production
          echo "VITE_GIFY_API_KEY=${{ secrets.VITE_GIFY_API_KEY }}" >> .env.production
          echo "VITE_GMAPS_API_KEY=${{ secrets.VITE_GMAPS_API_KEY }}" >> .env.production
          echo "VITE_API_ENDPOINT=${{ secrets.VITE_API_ENDPOINT }}" >> .env.production
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env.production
          mv .env.production ./frontend

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Deploy to S3
        run: aws s3 sync frontend/dist s3://esd.bchwy.com/ --delete --cache-control max-age=60 --acl public-read
